# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12efe224eba998e50fb250e1e955fa98506164145964f454610b1a647c412b46b889816c4aec86e0922f03def0ea59f8d08d27f11b8eddcec9353c140b4f51b1

test:
  secret_key_base: 78aec9b1c66a78e7ac3b7f6cabbd7fe4148fc4a4767c9506fd8eef973d7e3290ad6f1257ee69b6e3790bcb52f39bc33161bd56d873447b443ee7dabcc33713dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
